theme: jekyll-theme-cayman
title: Anomalias na Camada de Apresentação de Aplicativos Android
description: Apêndice online da dissertação de mestrado em Ciência da Computação submetido ao Instituto de Matemática e Estatística da Universidade de São Paulo (IME-USP).